#!/bin/sh -f

/bin/rm -f ./tmp_0
find /private/tmp -name 'org.x:0' -depth 2 -print 2>/dev/null > ./tmp_0

#cat ./tmp_0

lines=`wc -l ./tmp_0 | awk '{print $1}'`
#echo "lines ${lines}"

if [ "${lines}" = "0" ] ; then
  echo 'no DISPLAY file found under /private/tmp'
  exit
fi
if [ "${lines}" != "1" ] ; then
  echo 'more than one DISPLAY file found under /private/tmp'
  for file in $(cat tmp_0) ; do
    echo ${file}
  done
  exit
fi

for file in $(cat ./tmp_0) ; do
  echo ${file}
done

/bin/rm -f ./tmp_0
