#!/bin/sh -f

proc=$1

procs=`ps ax | grep ${proc} | grep -v grep`
if [ "${procs}" != "" ] ; then
  echo "find existing ${proc} processes :"
  #echo ${procs}
  ps ax | grep ${proc} | grep -v grep | awk '{print $1;}'
  echo "killing them..."
  ps ax | grep ${proc} | grep -v grep | awk '{system("kill -9 "$1);}'
fi
