#!/bin/bash -f

# It must be started with an absolute path in order
# to get directory of app on the remote machines.

app_dir=`dirname $0`

if [ "${app_dir:0:1}" != "/" ] ; then
  echo "This script must be started with an absolute path."
  exit
fi

${app_dir}/wall kill wall_
${app_dir}/kill_proc wall_
